eventd/eventd/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url('', include('eventdapp.urls')),
)

eventd/eventdapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'eventdapp.views.view_own_homepage'),
    url(r'login/$', login, {'template_name': 'eventdapp/login.html'}),
    url(r'logout/$', logout, {'next_page': '..'}),
    url(r'register/$', 'eventdapp.views.register'),

    url(r'event/(?P<event_id>\d+)/$', 'eventdapp.views.view_event'),
    url(r'event/create/$', 'eventdapp.views.create_event'),
    url(r'event/delete/(?P<event_id>\d+)/$','eventdapp.views.delete_event'),
    url(r'event/edit/(?P<event_id>\d+)/$', 'eventdapp.views.edit_event'),
    url(r'event/attend/(?P<event_id>\d+)/(?P<is_going>\w)/$',
        'eventdapp.views.attend_event'),
    url(r'event/invite/(?P<event_id>\d+)/$',
        'eventdapp.views.invite_friend'),
    url(r'event/search/$','eventdapp.views.search_event',
        {'content_type': 'text/html'}),
    url(r'event/search_xml/$','eventdapp.views.search_event',
        {'content_type': 'text/xml'}),
    
    url(r'user/(?P<user_id>\d+)/$','eventdapp.views.view_user'),  
    url(r'user/add/(?P<user_id>\d+)/$','eventdapp.views.add_friend'),
    url(r'respond/(?P<request_id>\d+)/(?P<is_confirm>\w)/$',
        'eventdapp.views.respond_addFriendRequest'),
)

eventd/eventdapp/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
  GENDERS = (("M","M"), ("F","F"))

  phone_number = models.CharField(max_length=20, blank=True)
  location = models.CharField(max_length=100, blank=True)
  dob = models.DateField(null=True, blank=True)
  gender = models.CharField(max_length=8, blank=True, choices=GENDERS)
  photo = models.ImageField(upload_to='user_photos', null=True, blank=True)
  friends = models.ManyToManyField('self', null=True, blank=True)

  user = models.ForeignKey(User, unique=True, related_name='profile')

  def __unicode__(self):
    return self.user.username

class Event(models.Model):
  CATEGORY_CHOICES = (("Sports","Sports"),("Party","Party"))
  
  title = models.CharField(max_length=100)
  description = models.CharField(max_length=2000)
  photo = models.ImageField(upload_to='event_photos',null=True, blank=True)
  start_time = models.DateTimeField()
  end_time = models.DateTimeField()
  place_text = models.CharField(max_length=200)
  place_longitude = models.FloatField(null=True, blank=True)
  place_latitude = models.FloatField(null=True, blank=True)
  category = models.CharField(max_length=20,choices=CATEGORY_CHOICES)
  owner=models.ForeignKey(User, blank=True)
  
  def __unicode__(self):
    return self.title
    
class Attendence(models.Model):
  PARTICIPATION_CHOICES = (("Y","Going"),("M","Maybe Going"),("N","Not Going"))

  @classmethod
  def is_valid_participation(cls, choice):
    return choice in [ch[0] for ch in cls.PARTICIPATION_CHOICES]

  @classmethod
  def get_remaining_choices(cls, current_choice=None):
    remaining_choices = [{'url':ch[0], 'disp':ch[1]} for ch in
                         cls.PARTICIPATION_CHOICES if ch[0] != current_choice]
    if current_choice == None:
      del remaining_choices[-1]
    return remaining_choices
  
  participant = models.ForeignKey(User)
  event = models.ForeignKey("Event")
  unique_together = (participant, event)
  participation = models.CharField(max_length=15, choices=PARTICIPATION_CHOICES)
  isInvited = models.BooleanField()
  
  def __unicode__(self):
    return self.event.title+"attendence"

class AddFriendRequest(models.Model):
  requester = models.ForeignKey(User,related_name='requester')
  requestee = models.ForeignKey(User,related_name='requestee')
 

eventd/eventdapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from eventdapp.models import Event, UserProfile

class CustomUserCreationForm(UserCreationForm):
  GENDERS = (('',''), ("M","M"), ("F","F"))

  email = forms.EmailField(required=True)
  gender = forms.ChoiceField(required=False, choices=GENDERS)
  phone_number = forms.CharField(required=False)
  location = forms.CharField(required=False)
  dob = forms.DateField(required=False)
  photo = forms.ImageField(required=False)
 
  class Meta:
    model = User
    fields = ("username", "email", "password1", "password2", 'gender',
              'phone_number', 'location', 'dob', 'photo')
 
  def save(self, commit=True):
    user = super(CustomUserCreationForm, self).save(commit=False)
    user.email = self.cleaned_data["email"]

    user_profile = UserProfile()
    user_profile.gender = self.cleaned_data["gender"]
    user_profile.phone_number = self.cleaned_data["phone_number"]
    user_profile.location = self.cleaned_data["location"]
    user_profile.dob = self.cleaned_data["dob"]
    user_profile.photo = self.cleaned_data["photo"]

    if commit:
      user.save()
      user_profile.user = user
      user_profile.save()
    return user

class EventForm(ModelForm):
  class Meta:
    model = Event
    exclude = ('owner',)
    widgets = {'place_longitude': forms.HiddenInput(),
               'place_latitude': forms.HiddenInput()}

  def __init__(self, *args, **kwargs):
    self.request = kwargs.pop("request")
    super(ModelForm, self).__init__(*args, **kwargs)

  def save(self, commit=True):
    event = super(ModelForm, self).save(commit=False)
    event.owner = self.request.user

    if commit:
      event.save()
    return event

eventd/eventdapp/views.py
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from eventdapp.models import AddFriendRequest
from eventdapp.models import Attendence, Event, UserProfile
from eventdapp.forms import CustomUserCreationForm, EventForm
from eventdapp.utils import is_valid_latlng, content_type_from, ext_from

def register(request):
  if request.method == 'POST':
    form = CustomUserCreationForm(request.POST, request.FILES)
    if form.is_valid():
      new_user = form.save()
      return HttpResponseRedirect("/")
  else:
    form = CustomUserCreationForm()

  template = "eventdapp/register.%s" % ext_from(request)

  return render(request, template, {
    'form': form,
  }, content_type=content_type_from(request))

def view_event(request, event_id):
  event = Event.objects.get(pk=event_id)
  owner_id = event.owner.id
  
  #determine whether the user has activated the participation status
  attendence = Attendence.objects.filter(event__pk = event.id, participant__pk = request.user.id)
  
  attendence_choices = Attendence.get_remaining_choices(
                          attendence[0].participation if attendence.exists() else None)
  template_vars = {
    'event': event,
    'attendence_choices': attendence_choices,
    'is_own': (request.user.id == owner_id),
    'share_subject': 'Check out this event!',
    'share_body': "Check out the event at" + '%0D%0A%0D%0A' + \
                  request.build_absolute_uri(),
    }
  if attendence.exists():
    template_vars['status'] = attendence[0].get_participation_display()

  template = 'eventdapp/event.%s' % ext_from(request)

  return render(request, template, template_vars, \
                content_type=content_type_from(request))

def create_event(request):
  return display_event_form(request, redirect="/")

def delete_event(request, event_id):
  if not request.user.is_authenticated():
    return HttpResponseRedirect("/login/")
  user_id = request.user.id 
  event = Event.objects.get(pk=event_id)
  owner_id = event.owner.id
  if user_id == owner_id:
    event.delete()
    return HttpResponseRedirect("/")
  else:
    return render(request, 'eventdapp/nopermit.html',{
      'type' : "delete",
    })
  
def edit_event(request, event_id):
  if not request.user.is_authenticated():
    return HttpResponseRedirect("/login/")
  user_id = request.user.id 
  event = Event.objects.get(pk=event_id)
  owner_id = event.owner.id
  if user_id == owner_id:
    return display_event_form(request, redirect="../../{}".format(event.id), instance=event)
  else:
    return render(request, 'eventdapp/nopermit.html',{
      'type' : "edit",
    })
    
def display_event_form(request, **kwargs):
  if not request.user.is_authenticated():
    return HttpResponseRedirect("/login/")
  redirect_addr = kwargs.pop("redirect")
  if request.method == 'POST':
    form = EventForm(request.POST, request.FILES, request=request, **kwargs)
    if form.is_valid():
      new_event = form.save()
      return HttpResponseRedirect(redirect_addr)
  else:
    form = EventForm(request=request, **kwargs)

  return render(request, 'eventdapp/event_form.html', {
    'form': form,
  })

def view_own_homepage(request):
  if not request.user.is_authenticated():
    return HttpResponseRedirect("/login/")
  return view_user(request, request.user.id)

def view_user(request, user_id):
  user = User.objects.get(pk=user_id)
  username = user.username
  user_profile_id = user.get_profile().id

  own_events = Event.objects.filter(owner=user)
  participation_event_ids = Attendence.objects.filter(participant=user) \
                              .values_list('event_id')
  participation_events = Event.objects \
                           .filter(id__in=participation_event_ids)
  events = own_events | participation_events

  addFriendRequests = AddFriendRequest.objects \
                        .filter(requester=request.user, requestee=user)
  has_added = addFriendRequests.exists()
  
  #check whether has friendship
  is_friend = False
  if len(request.user.get_profile().friends \
       .filter(id=user_profile_id)) != 0:
    is_friend = True

  allAddFriendRequests = AddFriendRequest.objects.filter(requestee=user)

  template = 'eventdapp/user.%s' % ext_from(request)

  return render(request, template, {
    'username': username,
    'events': events,
    "user_id": user_id,
    'is_self': (request.user.id == int(user_id)), 
    'is_friend': is_friend,
    'has_added': has_added,
    'allAddFriendRequests': allAddFriendRequests,
  }, content_type=content_type_from(request))  

def add_friend(request, user_id):
  user = User.objects.get(pk=user_id)
  
  addFriendRequest = AddFriendRequest()
  addFriendRequest.requester = request.user
  addFriendRequest.requestee = user
  addFriendRequest.save()
  return HttpResponseRedirect(("/user/{}").format(user_id))

def respond_addFriendRequest(request, request_id, is_confirm):
  addFriendRequest = AddFriendRequest.objects.get(pk=request_id)
  if is_confirm == 'y':
    requester = addFriendRequest.requester
    requestee = addFriendRequest.requestee
    requester.get_profile().friends.add(requestee.get_profile())
    requestee.get_profile().friends.add(requester.get_profile())  

  addFriendRequest.delete()
  return HttpResponseRedirect("/")

def invite_friend(request, event_id):
  if request.method == 'POST':
    event = Event.objects.get(pk=event_id)
    selected_friendList = request.POST.getlist('friendList')

    for selected_friend_id in selected_friendList:
      selected_friend = User.objects.get(pk=selected_friend_id)     
      attendence = Attendence()
      attendence.participant = selected_friend
      attendence.event = event
      isInvited = True
      attendence.save()
      
    return HttpResponseRedirect(("../../{}").format(event_id))

  else:
    friendProfileList = request.user.get_profile().friends.all()
    friendList = []
  
    if friendProfileList.exists():
      for friendProfile in friendProfileList:    
        attendence = Attendence.objects \
             .filter(event_id=event_id,participant=friendProfile.user)[:1]  
        if len(attendence) == 0:
          friendList.append(friendProfile.user)

    return render(request, 'eventdapp/invite.html',{
      'friendList' : friendList,
      'event_id' : event_id,
    })

#three participation views: attend, maybe attend, not attend
def attend_event(request, event_id, is_going):
  event = Event.objects.get(pk=event_id)
  attendence = Attendence.objects.filter(event__pk = event.id, participant__pk = request.user.id)
  user = request.user

  is_going = is_going.upper()
  if not Attendence.is_valid_participation(is_going):
    raise Http404

  if not attendence.exists():
    new_attendence = Attendence()
    new_attendence.participant = user
    new_attendence.event = event
    new_attendence.participation = is_going
    new_attendence.save()    
  elif attendence.exists():
    att = attendence[0]
    att.participation = is_going
    att.save()
    
  return HttpResponseRedirect(("../../../{}").format(event.id))

def search_event(request, content_type='text/html'):  
  events = Event.objects.none()
  top_events = []
  other_events = []
  avg_lat, avg_lng = 38.0, -97.0
  zoom = 3
  template = 'eventdapp/search_result_event.html' \
             if content_type == 'text/html' \
             else 'eventdapp/search_result_event.xml'

  what = request.GET.get("what")
  lng = request.GET.get("lng")
  lat = request.GET.get("lat")
    
  if is_valid_latlng(lat, lng):
    lng = float(lng)
    lat = float(lat)
    tempRawEvent = Event.objects.raw("""
SELECT * FROM
  (SELECT id, place_latitude, place_longitude,
        (3959 * acos(cos(radians(%s)) * cos(radians(place_latitude)) *
                           cos(radians(place_longitude) - radians(%s)) +
                           sin(radians(%s)) * sin(radians(place_latitude))))
   AS distance
   FROM eventdapp_event) AS distances
WHERE distance < 20
ORDER BY distance
OFFSET 0
LIMIT 20;
""",[lat,lng,lat])
    for event in tempRawEvent:
      events = events | Event.objects.filter(pk=event.id)
    if what != None:
      what_tokens = what.split()

      # filter "what" from event title
      tempEvent1 = events
      for token in what_tokens:
        tempEvent1 = tempEvent1.filter(title__icontains=token)

      # filter "what" from event description
      tempEvent2 = events
      for token in what_tokens:
        tempEvent2 = tempEvent2.filter(description__icontains=token)

      # all candidate events
      events = tempEvent1 | tempEvent2 

    if events:
      num_events = float(events.count())
      avg_lng = sum(event.place_longitude for event in events) / num_events
      avg_lat = sum(event.place_latitude for event in events) / num_events
      zoom = 12
      
      for i, e in enumerate(events):
        if i < 2:
            top_events.append(e)
        else:
            other_events.append(e)
 
  return render(request, template,{
    'top_events': top_events,
    'events': other_events,
    'avg_lng': avg_lng,
    'avg_lat': avg_lat,
    'zoom': zoom,
  }, content_type=content_type)

eventd/templates/eventdapp/event.html
{% extends "base.html" %}

{% block title %}Event View{% endblock %}

{% block script %}
  <link rel="stylesheet" href="/static/stylesheets/header_all.css">
  <link rel="stylesheet" href="/static/stylesheets/event.css">
  <script type="text/javascript">
    function initialize() {
      var locText = "<a href=\"/event/{{ event.id }}/\" target=\"_blank\">{{ event.title }}</a><br /><br />{{ event.place_text }}";
      var latlng = new google.maps.LatLng({{ event.place_latitude }},
                                          {{ event.place_longitude }});
      var mapOptions = { center: latlng,
                         zoom: 13,
                         mapTypeId: google.maps.MapTypeId.ROADMAP };
      var map = new google.maps.Map(document.getElementById("map_canvas"),
                                    mapOptions);
      var marker = new google.maps.Marker({ map: map,
                                            title: locText,
                                            position: latlng });
      var infowindow = new google.maps.InfoWindow({ content: locText });
        
      google.maps.event.addListener(marker, 'click',
                               function() { infowindow.open(map,marker); });
    }
  </script>
{% endblock %}

{% block header %}
<div id="header_right_wrapper">
  <a href="/event/create/">
    <img id="create_event" src="/static/images/create_event.png">
  </a>
  <a href="" >
    <img id="friend_request" src="/static/images/friend_request.png"s>
  </a>  
  <a href="">
    <img id="event_request" src="/static/images/event_request.png"s>
  </a>  
  <a href="/logout/">Log out</a>
</div>
{% endblock %}

{% block content %}
      <div id="wrapper2">
        <div id="event_intro">
          <img id="event_intro_left" src="/static/images\event.png"></img>
          <div id="event_intro_right">
            <div id="event_intro_right_top">
              <h1>{{ event.title }}</h1>
              <div id="choice">
                {% if not is_own %}
                <div class="attendence_box">{{status}}</div>
                {% for choice in attendence_choices %}
                <div class="attendence_box">
                <a href="../attend/{{ event.id }}/{{ choice.url}}">
                {{ choice.disp }}</a>
                </div>
                {% endfor %}
                {% endif %}
                <h1>|</h1>
                <div class="share_box"> <a href="mailto:?subject={{ share_subject }}&body={{ share_body }}">Share</a></div>
                <div class="share_box"><a href="../invite/{{ event.id }}/">Invite</a></div>
              </div>
              <div>
                {% if is_own %}
                <div class="share_box"><a href="../delete/{{ event.id }}/">Delete</a></div>
                <div class="share_box"><a href="../edit/{{ event.id }}/">Edit</a></div>
                <br />
                {% endif %}
            </div>
            </div>
            <div id="event_intro_right_bottom">  
              <table>
                <tr>
                  <td class="key">Public Event</td>
                  <td class="value">By {{ event.owner.username }}</td>
                </tr>
                <tr>
                  <td class="key">Category</td>
                  <td class="value">{{ event.category }}</td>
                </tr>
                <tr>
                  <td class="key">Time</td>
                  <td class="value"><p>Friday, November 29, 2012</p>
                                    <p>6:30pm util 9:30pm in UTC +01</p>
                  </td>
                </tr>
                <tr>
                  <td class="key">Where</td>
                  <td class="value">{{ event.place_text }}</td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div id="main_section">
          <div id="main_section_left">
            <div id="event_detail">
              <h1>Event Detail</h1>
              <p>
                {{ event.description }}
              </p>
            </div>
            <div id="wall">Wall</div>
          </div>
          <div id="side_bar">
            <aside id="event_map"></aside>
              <div id="map_canvas" style="width:300px;height:300px"></div>
            </aside>
            <aside class="attendance">
              <a href=""><h1>Invited(99)</h1></a>
              <div class="attendance_people">
                <img class="attendance_single" src="/static/images\dave.png"></img>
                <img class="attendance_single" src="/static/images\dave.png"></img>
                <img class="attendance_single" src="/static/images\dave.png"></img>
                <img class="attendance_single" src="/static/images\dave.png"></img>
                <img class="attendance_single" src="/static/images\dave.png"></img>
                <img class="attendance_single" src="/static/images\dave.png"></img>
                <img class="attendance_single" src="/static/images\dave.png"></img>
                <img class="attendance_single" src="/static/images\dave.png"></img>
                <img class="attendance_single" src="/static/images\dave.png"></img>
                <img class="attendance_single" src="/static/images\dave.png"></img>
              </div>
            </aside>
            <aside class="attendance">
              <a href=""><h1>Going(21)</h1></a>
              <div class="attendance_people">
                <img class="attendance_single" src="/static/images\girl.png"></img>
                <img class="attendance_single" src="/static/images\girl.png"></img>
                <img class="attendance_single" src="/static/images\girl.png"></img>
                <img class="attendance_single" src="/static/images\girl.png"></img>
                <img class="attendance_single" src="/static/images\girl.png"></img>
                <img class="attendance_single" src="/static/images\girl.png"></img>
                <img class="attendance_single" src="/static/images\girl.png"></img>
                <img class="attendance_single" src="/static/images\girl.png"></img>
                <img class="attendance_single" src="/static/images\girl.png"></img>
                <img class="attendance_single" src="/static/images\girl.png"></img>
              </div>
            </aside>
            <aside class="attendance">
             <a href=""><h1>Maybe(32)</h1></a>
              <div class="attendance_people">
                <img class="attendance_single" src="/static/images\attendance_pic.png"></img>
                <img class="attendance_single" src="/static/images\attendance_pic.png"></img>
                <img class="attendance_single" src="/static/images\attendance_pic.png"></img>
                <img class="attendance_single" src="/static/images\attendance_pic.png"></img>
                <img class="attendance_single" src="/static/images\attendance_pic.png"></img>
                <img class="attendance_single" src="/static/images\attendance_pic.png"></img>
                <img class="attendance_single" src="/static/images\attendance_pic.png"></img>
                <img class="attendance_single" src="/static/images\attendance_pic.png"></img>
                <img class="attendance_single" src="/static/images\attendance_pic.png"></img>
                <img class="attendance_single" src="/static/images\attendance_pic.png"></img>
              </div>
            </aside>
          </div>
        </div>
      </div> 
{% endblock %}

{% block body-attr %}
  onload="initialize()"
{% endblock %}

eventd/templates/eventdapp/event_form.html
{% extends "base.html" %}

{% block title %}Event Form{% endblock %}

{% block style %}
  <link rel="stylesheet" media="all" type="text/css" href="http://code.jquery.com/ui/1.9.1/themes/smoothness/jquery-ui.css" />
  <link rel="stylesheet" type="text/css" href="/static/timepicker.css" />
  <link rel="stylesheet" href="/static/stylesheets/create_event.css">
  <link rel="stylesheet" href="/static/stylesheets/header_all.css">
{% endblock %}

{% block script %}
  <script
    src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js">
  </script>
  <script type="text/javascript"
    src="/static/jquery-ui-timepicker-addon.js">
  </script>
  <script type="text/javascript">
    var map;
    var places;
    var markers = [];

    function handleSubmit() {
      searchLocation();
      $("#event_form").submit();
    }

    function searchLocation() {
      for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(null);
      }
      markers = [];
      var address = $("#id_place_text").val();
      var geocoder = new google.maps.Geocoder();
      geocoder.geocode({address: address}, function(results, status) {
        places = results;
        fillLatLngInputs(places[0]);
        for (var i = 0; i < results.length; i++) {
          var loc = results[i].geometry.location;
          var marker = new google.maps.Marker({ map: map,
                                            //title: locText,
                                            position: loc });
          markers.push(marker);
          addListener(marker, i);
          map.setCenter(calcCenter(results));
          map.setZoom(calcZoom(results));
        }
      });
    }

    function fillLatLngInputs(loc) {
      var geoLoc = loc.geometry.location;
      $("#id_place_longitude").val(geoLoc.lng());
      $("#id_place_latitude").val(geoLoc.lat());
    }

    function addListener(marker, idx) {
      google.maps.event.addListener(marker, 'click',
            function() {
              $("#id_place_text").val(places[idx].formatted_address);
              fillLatLngInputs(places[idx]);
            });
    }

    function calcCenter(locs) {
      var avg_lat = 0.0;
      var avg_lng = 0.0;
      for (var i = 0; i < locs.length; i++) {
        avg_lng += locs[i].geometry.location.lng();
        avg_lat += locs[i].geometry.location.lat();
      }
      return new google.maps.LatLng(avg_lat / locs.length,
                                    avg_lng / locs.length);
    }

    function calcZoom(locs) {
      var GLOBE_WIDTH = 256;

      if (locs.length === 0)
        return 3;

      var west = 180.0;
      var east = -180.0;
      for (var i = 0; i < locs.length; i++) {
        var lng = locs[i].geometry.location.lng();
        if (lng < west)
          west = lng;
        if (lng > east)
          east = lng;
      }
      var angle = east - west;
      if (angle < 0) {
        angle += 360;
      }
      var zoom = Math.round(Math.log(100.0 * 360 / angle / GLOBE_WIDTH) /
                            Math.LN2);
      if (zoom === Infinity)
        zoom = 13;
      return zoom;
    }

    function initialize() {
      var latlng = new google.maps.LatLng(38.0, -97.0);
      var mapOptions = { center: latlng,
                         zoom: 3,
                         mapTypeId: google.maps.MapTypeId.ROADMAP };
      map = new google.maps.Map(document.getElementById("map_canvas"),
                                mapOptions);

      if ($("#id_place_text").val() != "")
        searchLocation();

      $("#id_place_text").attr("onblur","searchLocation();");

      $("#id_start_time").datetimepicker();
      $("#id_end_time").datetimepicker();
    }
  </script>
{% endblock %}

{% block content %}
<form id="event_form" action="" method="post" enctype="multipart/form-data" autocomplete="on" novalidate="novalidate">	
  <section class="section1">	
		<div id="what">
			<div class="title">
				What
			</div>
			    {{ form.title }}
			    {{ form.title.errors }}
				{{ form.description}}
				{{ form.description.errors }}
			    {{ form.category }}
			    {{ form.category.errors }}
			    {{ form.photo }}
			    {{ form.photo.errors }}
		</div>
		<div id="when">
			<div class="title">
				When
			</div>
            {{ form.start_time}}
            {{ form.start_time.errors }}
            {{ form.end_time}}
            {{ form.end_time.errors }}
		</div>
	</section>
	<section class="section1">
		<div id="where">
			<div class="title">
				Where
			</div>
			{{ form.place_text }}
			{{ form.place_text.errors }}
			<div id="map_canvas"></div>
		</div>
		<div id="who">
			<div class="title">
				Who
			</div>
				<input id="friend" name="friend" required="required" type="text" placeholder="Search Friends"/>
		</div>				
	</section>
	{{ form.place_latitude }}
	{{ form.place_longitude }}
			</form>
	
		<input id="submitbutton" type="button" onclick="handleSubmit()" value="Submit">

 
{% endblock %}

{% block header %}
    <div id="header_right_wrapper">
      <a href="/event/create/">
        <img id="create_event" src="/static/images/create_event.png">
      </a>
      <a href="" >
        <img id="friend_request" src="/static/images/friend_request.png"s>
      </a>  
      <a href="">
        <img id="event_request" src="/static/images/event_request.png"s>
      </a>  
      <a href="/logout/">Log out</a>
    </div>
{% endblock %}
{% block body-attr %}
  onload="initialize()"
{% endblock %}

eventd/templates/eventdapp/friend_list.html
{% extends "base.html" %}

{% block title %}Friend List{% endblock %}

{% block content %}
    {{event_id}}
    <form name="select_friend" action="http://127.0.0.1:8000/event/select_friend/{{event_id}}/" method="post">
    {% csrf_token %}
      {% for friend in friendList %}
        <input type="checkbox" name="friendList" value="{{ friend.id }}">{{friend.username}}<br>
      {% endfor %}
      <input type="submit" value="submit">
    </form>
{% endblock %}

eventd/templates/eventdapp/invite.html
{% extends "base.html" %}

{% block title %}Invite Friends{% endblock %}

{% block content %}
    {{event_id}}
    <form name="invite" action="" method="post">
      {% for friend in friendList %}
        <input type="checkbox" name="friendList" value="{{ friend.id }}">{{friend.username}}<br>
      {% endfor %}
      <input type="submit" value="submit">
    </form>
{% endblock %}

eventd/templates/eventdapp/nopermit.html
{% extends "base.html" %}

{% block title %}No Permit{% endblock %}

{% block content %}
Sorry, you don't have permission to {{type}} the event.

{% endblock %}

eventd/templates/eventdapp/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}
{% block script %}
  <link rel="stylesheet" href="/static/stylesheets/register.css">
{% endblock %}
{% block content %}
  <h1>Create an account</h1>

  <form enctype="multipart/form-data" action="" method="post">
    <div id="register_form">{{ form.as_p }}</div>
    <input type="submit" value="Create the account">
  </form>
{% endblock %}